/*
 * This source file was generated by the Gradle 'init' task
 */
package taller3;

public class App {

   public static void main(String[] args) {
   

   }

   /*
    * 1. Construya un algoritmo e implemente la función en Java Escribir_asc que
    * reciba tres números enteros diferentes
    * y devuelva en un String en orden ascendente con el siguiente formato:
    * "##### - ##### - #####", donde el primero es
    * el mayor de todos, el segundo el del medio, el tercero el menor de todos. Si
    * hay al menos dos números iguales,
    * devolverá el mensaje: "Error: La función no considera números iguales". Si
    * hay un error inesperado, deberá mostrar
    * el mensaje: "Ocurrió un error inesperado".
    */
  public static String Escribir_asc(int nro1, int nro2, int nro3){
      try {
        String txt_retornar="";
        int nro_mayor=0;
        int nro_medio=0;
        int nro_menor=0;

        if(nro1==nro2 || nro1==nro3 || nro2==nro3){
          return "Error: La función no considera números iguales";
        }
        if(nro1>nro2 && nro1>nro3){
          if(nro2>nro3){
          nro_mayor=nro1;
          nro_medio=nro2;
          nro_menor=nro3;
          }
          else if(nro3>nro2){
            nro_mayor=nro1;
            nro_medio=nro3;
            nro_menor=nro2;
            
          }
        }
        else if(nro2>nro3 && nro2>nro1){
          if(nro1>nro3){
          nro_mayor=nro2;
          nro_medio=nro1;
          nro_menor=nro3;
          }
          else if(nro3>nro1){
            nro_mayor=nro2;
            nro_medio=nro3;
            nro_menor=nro1;
          }
        }
        else if(nro3>nro2 && nro3>nro1){
          if(nro2>nro1){
          nro_mayor=nro3;
          nro_medio=nro2;
          nro_menor=nro1;
          }
          else if(nro1>nro2){
            nro_mayor=nro3;
            nro_medio=nro1;
            nro_menor=nro2;

          }
        }

        txt_retornar=nro_mayor+" - "+nro_medio+" - "+nro_menor;

        return txt_retornar;
      }
      catch (Exception e) {
        return "Ocurrió un error inesperado";
      }



   /*
    * 2. Construya un algoritmo e implemente la función en Java Obtener_cifras que
    * recibe un número entre 0 y 50.000
    * y devuelve byte con las cifras que tiene. Por ejemplo 10 tiene dos cifras,
    * 9999 tiene 4 cifras. Si el número
    * no está en el rango devuelve 0. Y si hay un error inesperado, devuelve -1.
    * 
    */
    public static byte Obtener_cifras(int numero){
        try {
           int numero_min =0;
           int numero_max=50000;
           int diez=10;
           int cien=100;
           int mil=1000;
           int diez_mil=10000;

           if (numero >= numero_min && numero <= numero_max ){
              if(numero<diez){
                 return 1;
              }
              else if (numero >=diez && numero<cien){
                 return 2;
              }
              else if (numero >= cien && numero<mil){
                 return 3;
              }
              else if (numero >=mil && numero < diez_mil){
                 return 4;
              }
              else{
                 return 5;
              }

           }
           else{
              return 0;
           }
        } catch (Exception e) {
          return -1;
        }
      }


   /*
    * 3. Construya un algoritmo e implemente la función en Java Clasificar_char que
    * recibe un caracter, y
    * devuelve un string de acuerdo con las siguientes condiciones: si es un
    * alfabético, deuvelve "ES LETRA";
    * si es numérico, devuelve "ES NUMERO" o si es un carácter especial, devuelve
    * "ESPECIAL".
    * Los caracteres se validan de acuerdo con la tabla ascii básica y lo explicado
    * en clase.
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * 
    */
    public static String Clasificar_char(char caracter){
          try {
              int caracter_ascii=(int)caracter;
              String txt_retornar="";

              if((caracter_ascii>=65 && caracter_ascii<=90)||(caracter_ascii>=97 && caracter_ascii<=122)){
                  txt_retornar= "ES LETRA";
              }
              else if(caracter_ascii>=48 && caracter_ascii<=57){
                  txt_retornar= "ES NUMERO";
              }else if((caracter_ascii>=33 && caracter_ascii<=47) || (caracter_ascii>=58 && caracter_ascii<=64)||(caracter_ascii>=123 && caracter_ascii<=126)){
                  txt_retornar= "ESPECIAL";
              }

              return txt_retornar;
          }
          catch (Exception e) {
              return "Ocurrió un error inesperado";
          }


      }


   /*
    * 
    * 4. Construya un algoritmo e implemente la función en Java
    * Hallar_division_exacta que pida dos números enteros,
    * calcule la división del primero sobre el segundo, y al final si la división
    * es exacta, devuelva "DIVISION EXACTA"
    * y de lo contrario devuelva "DIVISION NO EXACTA". (Exacta significa que tiene
    * cociente, pero no residuo).
    * 
    * Si alguno de los dos números que recibe es cero o negativo, devuelva
    * "NO SE ADMITE CERO O NEGATIVOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * Nota: Revise el funcionamiento del operador mod que le puede ayudar.
    * 
    * 
    * 
    */
   public static String Hallar_division_exacta(int nro1, int nro2){
          try {
              String txt_retornar="";
              
             if(nro1<=0 || nro2<=0){
                 return "NO SE ADMITE CERO O NEGATIVOS";
             }
              
             if(nro1%nro2==0){
                 txt_retornar="DIVISION EXACTA";
             }
             else{
                 txt_retornar="DIVISION NO EXACTA";
             }
              return txt_retornar;
          }
          catch (Exception e) {
              return "Ocurrió un error inesperado";
          }
      }
   

   /*
    * 5. En la siguiente tabla se encuentra la información de las habitaciones de
    * una finca hotel:
    * 
    * Habitación Camas Planta    AA/VENTILADOR
    *    101         2     Primera     AA
    *    102         1     Primera     VE
    *    201         3     Segunda     AA
    *    202         2     Segunda     VE
    *    301         2     Tercera     AA
    * 
    * 
    * Construya un algoritmo e implemente la función en Java Consultar_hab que
    * reciba en un byte el número de camas
    * y en un string si desea VE o AA, y deuvelva en un texto el o los números de
    * habitación que cumplen ese requisito.
    * Si son varias habitaciones, devuelvalas separadas por el caracter |
    * (normalmente, al lado izquierdo de la tecla del 1).
    * Ejemplo: "101|301"
    * Si el número de camas no está entre 1 y 3 o el string es diferente a AA o VE,
    * devuelva "DATOS NO VÁLIDOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    */

   public static String Consultar_hab(byte camas, String tipo_hab){
          try {
              String txt_retornar="";
                if(camas<1 || camas>3 || (!tipo_hab.equals("VE") && !tipo_hab.equals("AA"))){
                    return "DATOS NO VÁLIDOS";
                }
                    
              if(camas==1 && tipo_hab=="VE"){
                  txt_retornar= "102";
              }
              else if(camas==2){
                  if(tipo_hab=="AA"){
                      txt_retornar="101|301";
                  }else{
                      txt_retornar="202";
                  }
              }
              else if(camas==3){
                  txt_retornar="201";
              }
              
              return txt_retornar;
              
              }
              catch (Exception e) {
                  return "Ocurrió un error inesperado";
              }
      }
   
   /*
    * 
    * 6. Un restaurante vende 3 platos. Si el cliente solicita el plato 1, le dan
    * el postre gratis; si selecciona los platos
    * 1 y 2, le dan la bebida gratis y si selecciona los platos 1,2 y 3, le dan
    * postre y bebida.
    * Construya un algoritmo e implemente la función Obtener_obs en Java que reciba
    * 3 booleanos, uno para cada plato y en
    * un String devuelva el obsequio ganado en mayúscula, así: "BEBIDA", "POSTRE",
    * "BEBIDA Y POSTRE".
    * Si los 3 platos vienen en false, , devuelva "PLATOS NO VÁLIDOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    */

   public static String Obtener_obs(boolean plato1, boolean plato2, boolean plato3){
          try {
              String txt_retornar="";
              
               if(plato1==false && plato2==false && plato3==false){
                   return "PLATOS NO VÁLIDOS";
               }

              if(plato1==true && plato2==true && plato3==true){
                  txt_retornar="BEBIDA Y POSTRE";
              }else if(plato1==true && plato2==true){
                  txt_retornar="BEBIDA";
              }else if(plato1==true){
                  txt_retornar="POSTRE";
              }
                
            return txt_retornar;
              
            }
            catch (Exception e) {
                return "Ocurrió un error inesperado";
            }
      }







   /*
    * 7. Un grupo de amigos hace un sorteo semanalmente con pelotas de ping pong,
    * para saber quién invita y a qué  la próxima salida.
    * Las opciones dependen del color que sacan en cada bola y son:
    * 
    * verde: Invita a las cervezas
    * azul: Invita a la pizza
    * rojo: Invita al postre
    * amarillo: Paga el parqueadero de todos
    * blanco o negro: Vaya y disfrute
    * Si la función recibe algo diferente a los colores dados, debe retornar
    * "Error en el color".
    * 
    * Se necesita una función en java Conocer_invitacion que reciba un string con
    * el color de la bola y retorna un
    * String con exactamente el texto de la invitación correspondiente.
    * 
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * 
    */
    public static String Conocer_invitacion(String color){
        try {
            String txt_retornar="";
           switch (color.toLowerCase()) {
              case "verde":
                 txt_retornar="Invita a las cervezas";
                 break;

              case "azul":
                     txt_retornar="Invita a la pizza";

                 break;

              case "rojo":
                     txt_retornar= "Invita al postre";

                 break;

              case "amarillo":
                     txt_retornar= "Paga el parqueadero de todos";

                 break;

              case "blanco":
                     txt_retornar= "Vaya y disfrute";

                 break;

              case "negro":
                     txt_retornar= "Vaya y disfrute";

                 break;

              default:
                 return "Error en el color";
           }
            return txt_retornar;

        }
        catch (Exception e) {
           return "Ocurrió un error inesperado";
        }

      }

}

